
export type Flashcard = {
  id: string;
  question: string;
  answer: string;
};

export type MCQ = {
  id: string;
  question: string;
  options: string[];
  correctAnswer: string;
};

export type Reel = {
  id: string;
  title: string;
  content: string;
  imageId: string;
};

export type Chapter = {
  id: string;
  title: string;
  content: string;
  summary: string;
  keyTerms: { term: string }[];
  flashcards: Flashcard[];
  mcqs: MCQ[];
  reels: Reel[];
};

export const syllabus: Chapter[] = [
  {
    id: 'the-world-since-1991',
    title: 'The World since 1991',
    content: `
The world has changed dramatically since 1991, marked by the end of the Cold War and the dissolution of the Soviet Union. This era saw the rise of the United States as the sole superpower, leading to a unipolar world order. Key events include the Gulf War, the rise of the internet, and the expansion of NATO.
Concepts like {globalization} have become central, describing the increased interconnectedness of societies.
    `,
    summary: 'An overview of the major political, economic, and social transformations that have shaped the world since the end of the Cold War in 1991.',
    keyTerms: [{ term: 'globalization' }],
    flashcards: [
        { id: 'fc-1-1', question: 'What were the main consequences of the disintegration of the Soviet Union?', answer: 'The end of the Cold War, the emergence of a unipolar world led by the US, the independence of 15 new countries, and a shift in international power dynamics.' },
        { id: 'fc-1-2', question: 'What is a unipolar world order?', answer: 'An international system in which one state exercises most of the cultural, economic, and military influence. After 1991, the United States was considered the sole superpower.' },
        { id: 'fc-1-3', question: 'What was the "Third Way" in post-Cold War politics?', answer: 'A political position embracing a varied blend of right-wing economic and left-wing social policies, adopted by leaders like Tony Blair in the UK and Bill Clinton in the US during the 1990s.' },
        { id: 'fc-1-4', question: 'What was the significance of the first Gulf War (1990-1991)?', answer: 'It was the first major international conflict after the Cold War, where a US-led coalition repelled the Iraqi invasion of Kuwait, reinforcing the US\'s role as a global leader.' },
        { id: 'fc-1-5', question: 'How did the role of NATO change after 1991?', answer: 'NATO transformed from a purely defensive alliance against the Soviet Union to an organization involved in crisis management and peacekeeping operations, expanding its membership to include former Warsaw Pact countries.' },
        { id: 'fc-1-6', question: 'What was the Dayton Agreement?', answer: 'A peace agreement signed in 1995 that ended the Bosnian War, a brutal ethnic conflict that followed the breakup of Yugoslavia.' },
        { id: 'fc-1-7', question: 'What characterized the "dot-com bubble" of the late 1990s?', answer: 'A rapid rise in U.S. technology stock equity valuations fueled by investments in Internet-based companies, which was followed by a sharp crash in 2000-2001.' },
        { id: 'fc-1-8', question: 'What is the significance of the Kyoto Protocol?', answer: 'An international treaty adopted in 1997 that committed state parties to reduce greenhouse gas emissions, representing one of the first major global efforts to address climate change.' },
        { id: 'fc-1-9', question: 'What was the "War on Terror"?', answer: 'The global military, political, legal, and conceptual struggle against terrorist organizations and the regimes accused of supporting them, launched by the U.S. following the 9/11 attacks.' },
        { id: 'fc-1-10', question: 'What was the Arab Spring?', answer: 'A series of anti-government protests, uprisings, and armed rebellions that spread across much of the Arab world in the early 2010s.' },
        { id: 'fc-1-11', question: 'How did the 2008 financial crisis impact global politics?', answer: 'It led to a global recession, increased scrutiny of financial regulation, and fueled public discontent that contributed to the rise of populist movements.' },
        { id: 'fc-1-12', question: 'What is meant by the rise of "populism" in the 21st century?', answer: 'A political approach that strives to appeal to ordinary people who feel that their concerns are disregarded by established elite groups. It often features anti-establishment and nationalist rhetoric.' },
        { id: 'fc-1-13', question: 'What is Brexit?', answer: 'The withdrawal of the United Kingdom from the European Union, following a referendum in June 2016. It marked a significant event in the history of European integration.' },
        { id: 'fc-1-14', question: 'What is the significance of China\'s entry into the World Trade Organization (WTO) in 2001?', answer: 'It integrated China more deeply into the global economy, accelerating its rise as a major economic power.' },
        { id: 'fc-1-15', question: 'Who was the first post-apartheid president of South Africa?', answer: 'Nelson Mandela, who was elected in 1994 after spending 27 years in prison for his anti-apartheid activism.' },
        { id: 'fc-1-16', question: 'What is meant by a "failed state"?', answer: 'A state whose political or economic system has become so weak that the government is no longer in control. Somalia in the 1990s is often cited as an example.' },
        { id: 'fc-1-17', question: 'What was the International Criminal Court (ICC) established to do?', answer: 'Established by the Rome Statute in 1998, the ICC investigates and prosecutes individuals for the most serious crimes of international concern: genocide, war crimes, and crimes against humanity.' },
        { id: 'fc-1-18', question: 'What are BRICS nations?', answer: 'An acronym for a group of five major emerging economies: Brazil, Russia, India, China, and South Africa, which have sought to increase their cooperation.' },
        { id: 'fc-1-19', question: 'What was the "Orange Revolution"?', answer: 'A series of protests and political events that took place in Ukraine from late 2004 to early 2005, in the immediate aftermath of the run-off vote of the 2004 presidential election.' },
        { id: 'fc-1-20', question: 'What is the "digital divide"?', answer: 'The gap between demographics and regions that have access to modern information and communications technology and those that don\'t or have restricted access.' },
    ],
    mcqs: [
        { id: 'mcq-1-1', question: 'The dissolution of the Soviet Union officially occurred in which year?', options: ['1989', '1990', '1991', '1992'], correctAnswer: '1991' },
        { id: 'mcq-1-2', question: 'Which of these is NOT a country that emerged from the former Yugoslavia?', options: ['Serbia', 'Croatia', 'Slovakia', 'Bosnia and Herzegovina'], correctAnswer: 'Slovakia' },
        { id: 'mcq-1-3', question: 'The Maastricht Treaty, signed in 1992, led to the creation of what entity?', options: ['The United Nations', 'The European Union', 'NATO', 'The World Trade Organization'], correctAnswer: 'The European Union' },
        { id: 'mcq-1-4', question: 'The term "soft power" was coined by which political scientist?', options: ['Francis Fukuyama', 'Samuel Huntington', 'Joseph Nye', 'John Mearsheimer'], correctAnswer: 'Joseph Nye' },
        { id: 'mcq-1-5', question: 'The 9/11 terrorist attacks led to the US-led invasion of which country?', options: ['Iraq', 'Iran', 'Syria', 'Afghanistan'], correctAnswer: 'Afghanistan' },
        { id: 'mcq-1-6', question: 'The end of apartheid in South Africa is most closely associated with which leader?', options: ['F.W. de Klerk', 'Nelson Mandela', 'Thabo Mbeki', 'Desmond Tutu'], correctAnswer: 'Nelson Mandela' },
        { id: 'mcq-1-7', question: 'The Bosnian War in the 1990s was an ethnic conflict that followed the breakup of which country?', options: ['Czechoslovakia', 'Soviet Union', 'Yugoslavia', 'Austria-Hungary'], correctAnswer: 'Yugoslavia' },
        { id: 'mcq-1-8', question: 'Which U.S. President oversaw the end of the Cold War?', options: ['Ronald Reagan', 'George H.W. Bush', 'Bill Clinton', 'George W. Bush'], correctAnswer: 'George H.W. Bush' },
        { id: 'mcq-1-9', question: 'The 1994 Rwandan genocide involved the mass killing of which ethnic group?', options: ['Hutu', 'Tutsi', 'Twa', 'Zulu'], correctAnswer: 'Tutsi' },
        { id: 'mcq-1-10', question: 'Which event is considered the symbolic end of the Cold War?', options: ['The fall of the Berlin Wall', 'The dissolution of the Soviet Union', 'The signing of the START I treaty', 'The unification of Germany'], correctAnswer: 'The fall of the Berlin Wall' },
        { id: 'mcq-1-11', question: 'The 2003 invasion of Iraq was justified by the US and UK based on allegations of what?', options: ['Sponsorship of Al-Qaeda', 'Possession of weapons of mass destruction', 'Human rights abuses against the Kurds', 'The invasion of Kuwait'], correctAnswer: 'Possession of weapons of mass destruction' },
        { id: 'mcq-1-12', question: 'The G20, a forum for major economies, became more prominent after which global event?', options: ['The 9/11 attacks', 'The 2008 financial crisis', 'The Arab Spring', 'The Eurozone debt crisis'], correctAnswer: 'The 2008 financial crisis' },
        { id: 'mcq-1-13', question: 'Which country did NOT join NATO in the first wave of post-Cold War expansion in 1999?', options: ['Poland', 'Hungary', 'Czech Republic', 'Romania'], correctAnswer: 'Romania' },
        { id: 'mcq-1-14', question: 'Francis Fukuyama\'s "The End of History and the Last Man" argued for the universalization of what?', options: ['Socialist democracy', 'Western liberal democracy', 'Authoritarian capitalism', 'Islamic theocracy'], correctAnswer: 'Western liberal democracy' },
        { id: 'mcq-1-15', question: 'The concept of a "clash of civilizations" was proposed by:', options: ['Joseph Nye', 'Francis Fukuyama', 'Samuel Huntington', 'Henry Kissinger'], correctAnswer: 'Samuel Huntington' },
        { id: 'mcq-1-16', question: 'The "Rose Revolution" (2003) and "Cedar Revolution" (2005) were pro-democracy movements in which countries, respectively?', options: ['Ukraine and Lebanon', 'Georgia and Lebanon', 'Ukraine and Syria', 'Georgia and Syria'], correctAnswer: 'Georgia and Lebanon' },
        { id: 'mcq-1-17', question: 'What is the primary currency of the European Union?', options: ['Pound', 'Franc', 'Mark', 'Euro'], correctAnswer: 'Euro' },
        { id: 'mcq-1-18', question: 'The "pivot to Asia" was a foreign policy strategy most associated with which US administration?', options: ['George W. Bush', 'Barack Obama', 'Donald Trump', 'Joe Biden'], correctAnswer: 'Barack Obama' },
        { id: 'mcq-1-19', question: 'The 2015 Paris Agreement is a landmark international accord to combat what?', options: ['Nuclear proliferation', 'Terrorism', 'Cybercrime', 'Climate change'], correctAnswer: 'Climate change' },
        { id: 'mcq-1-20', question: 'Which of the following social media platforms was founded earliest?', options: ['Facebook', 'Twitter', 'Instagram', 'TikTok'], correctAnswer: 'Facebook' },
    ],
    reels: [
      { id: 'reel-1-1', title: 'End of Cold War', content: 'The collapse of the Soviet Union reshaped global politics.', imageId: 'reel-1-1' },
      { id: 'reel-1-2', title: 'Rise of Internet', content: 'Digital revolution connecting the world.', imageId: 'reel-1-2' },
    ],
  },
  {
    id: 'globalisation',
    title: 'Key Concepts and Issues since 1991: Globalisation',
    content: `
{Globalisation} refers to the process of interaction and integration among people, companies, and governments worldwide. It has been accelerated by advances in transportation and communication technology. It has economic, political, and cultural manifestations. Economic globalization involves the integration of international financial markets and the growth of transnational corporations.
    `,
    summary: 'This chapter explores the multifaceted concept of globalization, examining its economic, political, and cultural impacts on the modern world.',
    keyTerms: [{ term: 'Globalisation' }],
    flashcards: [
        { id: 'fc-2-1', question: 'What are the three main dimensions of globalization?', answer: 'Economic globalization (flow of capital/goods), Political globalization (influence of international organizations), and Cultural globalization (spread of ideas/values).' },
        { id: 'fc-2-2', question: 'What is a Transnational Corporation (TNC)?', answer: 'A company that operates in more than one country. TNCs are key drivers of economic globalization.' },
        { id: 'fc-2-3', question: 'What are some criticisms of globalization?', answer: 'It can lead to increased inequality, erosion of local cultures, environmental degradation, and a "race to the bottom" in labor standards.' },
        { id: 'fc-2-4', question: 'What is the role of the World Trade Organization (WTO)?', answer: 'The WTO is an intergovernmental organization that regulates and facilitates international trade. It sets the rules of trade between nations.' },
        { id: 'fc-2-5', question: 'How has technology fueled globalization?', answer: 'The internet, mobile phones, and containerization have drastically reduced the costs of communication and transportation, making global interaction easier and faster.' },
        { id: 'fc-2-6', question: 'What is neoliberalism?', answer: 'A policy model that emphasizes the value of free-market competition, minimal state intervention in the economy, and privatization. It is strongly associated with the rise of economic globalization.' },
        { id: 'fc-2-7', question: 'What is cultural homogenization?', answer: 'The idea that globalization leads to a reduction in cultural diversity through the popularization and diffusion of a wide array of cultural symbols — not just physical objects but customs, ideas and values.' },
        { id: 'fc-2-8', question: 'What is "glocalization"?', answer: 'The practice of conducting business according to both local and global considerations. It describes how global products are adapted to suit local tastes (e.g., McDonald\'s menus varying by country).' },
        { id: 'fc-2-9', question: 'What is a global supply chain?', answer: 'A worldwide network of suppliers, manufacturers, distributors, and retailers involved in creating and delivering a product to the final customer.' },
        { id: 'fc-2-10', question: 'What is outsourcing?', answer: 'The business practice of hiring a party outside a company to perform services or create goods that were traditionally performed in-house by the company\'s own employees and staff.' },
        { id: 'fc-2-11', question: 'What does the term "race to the bottom" refer to in the context of globalization?', answer: 'A situation where countries lower labor standards, environmental protections, and taxes to attract foreign investment from TNCs.' },
        { id: 'fc-2-12', question: 'What is Foreign Direct Investment (FDI)?', answer: 'An investment made by a firm or individual in one country into business interests located in another country.' },
        { id: 'fc-2-13', question: 'How does political globalization manifest?', answer: 'Through the growing influence of international organizations like the UN and the EU, and the increasing importance of international law and norms.' },
        { id: 'fc-2-14', question: 'What is the "Washington Consensus"?', answer: 'A set of 10 economic policy prescriptions considered to constitute the "standard" reform package promoted for crisis-wracked developing countries by Washington, D.C.-based institutions such as the IMF and World Bank.' },
        { id: 'fc-2-15', question: 'What is protectionism?', answer: 'The economic policy of restricting imports from other countries through methods such as tariffs on imported goods, import quotas, and a variety of other government regulations.' },
        { id: 'fc-2-16', question: 'Who are "Davos Man"?', answer: 'A term coined by Samuel Huntington for the global elite, who are seen as having more in common with each other than with their fellow countrymen.' },
        { id: 'fc-2-17', question: 'What is the role of the International Monetary Fund (IMF)?', answer: 'An international organization that works to foster global monetary cooperation, secure financial stability, facilitate international trade, and promote sustainable economic growth.' },
        { id: 'fc-2-18', question: 'What is a "non-governmental organization" (NGO)?', answer: 'A non-profit, voluntary citizens\' group which is organized on a local, national or international level. Many NGOs are active in protesting or promoting aspects of globalization.' },
        { id: 'fc-2-19', question: 'What is the "digital silk road"?', answer: 'A component of China\'s Belt and Road Initiative that aims to build digital connectivity and infrastructure in participating countries.' },
        { id: 'fc-2-20', question: 'What is cosmopolitanism?', answer: 'The ideology that all human beings belong to a single community, based on a shared morality. It is often seen as the cultural and philosophical counterpart to globalization.' },
    ],
    mcqs: [
        { id: 'mcq-2-1', question: 'Which of the following is an example of cultural globalization?', options: ['The establishment of the World Bank', 'The spread of McDonald\'s restaurants worldwide', 'A free trade agreement between two countries', 'A United Nations resolution'], correctAnswer: 'The spread of McDonald\'s restaurants worldwide' },
        { id: 'mcq-2-2', question: 'The "Bretton Woods" institutions, which are pillars of economic globalization, include:', options: ['The IMF and World Bank', 'NATO and the Warsaw Pact', 'The EU and ASEAN', 'Amnesty International and Greenpeace'], correctAnswer: 'The IMF and World Bank' },
        { id: 'mcq-2-3', question: 'The term "global village," describing a world made smaller by technology, was popularized by:', options: ['Karl Marx', 'Marshall McLuhan', 'Adam Smith', 'Mao Zedong'], correctAnswer: 'Marshall McLuhan' },
        { id: 'mcq-2-4', question: 'Anti-globalization protests first gained major international attention during a meeting of which organization in Seattle in 1999?', options: ['G20', 'UN', 'IMF', 'WTO'], correctAnswer: 'WTO' },
        { id: 'mcq-2-5', question: 'What is a primary characteristic of economic globalization?', options: ['Increased tariff barriers', 'Reduced international trade', 'Integration of financial markets', 'Strengthening of national currencies'], correctAnswer: 'Integration of financial markets' },
        { id: 'mcq-2-6', question: 'Which of these is NOT a typical characteristic of neoliberal economic policy?', options: ['Privatization', 'Deregulation', 'Expansion of the welfare state', 'Free trade'], correctAnswer: 'Expansion of the welfare state' },
        { id: 'mcq-2-7', question: 'The concept of "McDonaldization," referring to the spread of rational and efficient principles, was developed by:', options: ['Benjamin Barber', 'George Ritzer', 'Thomas Friedman', 'Naomi Klein'], correctAnswer: 'George Ritzer' },
        { id: 'mcq-2-8', question: 'A tariff is a tax on:', options: ['Exported goods', 'Imported goods', 'Domestically produced goods', 'Services'], correctAnswer: 'Imported goods' },
        { id: 'mcq-2-9', question: 'NAFTA (North American Free Trade Agreement) was a trade bloc between the USA, Canada, and which other country?', options: ['Brazil', 'Argentina', 'Mexico', 'United Kingdom'], correctAnswer: 'Mexico' },
        { id: 'mcq-2-10', question: 'Thomas Friedman\'s book "The World Is Flat" is a metaphor for:', options: ['The decline of Western power', 'A level playing field in global commerce due to technology', 'The increasing threat of climate change', 'The rise of cultural conflict'], correctAnswer: 'A level playing field in global commerce due to technology' },
        { id: 'mcq-2-11', question: 'The "Stiglitz critique" of globalization argues that it:', options: ['Has been perfectly managed by the IMF and World Bank', 'Has primarily benefited developed countries at the expense of developing ones', 'Leads to cultural unity and understanding', 'Is a myth and not a real phenomenon'], correctAnswer: 'Has primarily benefited developed countries at the expense of developing ones' },
        { id: 'mcq-2-12', question: 'The movement of skilled professionals from developing to developed countries is known as:', options: ['Brain drain', 'Outsourcing', 'Offshoring', 'Capital flight'], correctAnswer: 'Brain drain' },
        { id: 'mcq-2-13', question: 'Which invention was most crucial for the physical movement of goods in the age of globalization?', options: ['The airplane', 'The telegraph', 'The shipping container', 'The satellite'], correctAnswer: 'The shipping container' },
        { id: 'mcq-2-14', question: 'The idea of a "borderless world" is most closely associated with which aspect of globalization?', options: ['Economic', 'Political', 'Cultural', 'Military'], correctAnswer: 'Economic' },
        { id: 'mcq-2-15', question: 'Which of the following is a major argument IN FAVOR of globalization?', options: ['It preserves local traditions', 'It promotes economic efficiency and growth', 'It reduces the power of multinational corporations', 'It guarantees job security for all'], correctAnswer: 'It promotes economic efficiency and growth' },
        { id: 'mcq-2-16', question: 'The World Social Forum is a gathering of civil society organizations that often presents itself as an alternative to:', options: ['The United Nations General Assembly', 'The World Economic Forum in Davos', 'The Olympic Games', 'The G7 Summit'], correctAnswer: 'The World Economic Forum in Davos' },
        { id: 'mcq-2-17', question: 'Which currency is the world\'s primary reserve currency?', options: ['Euro', 'Yen', 'Pound Sterling', 'US Dollar'], correctAnswer: 'US Dollar' },
        { id: 'mcq-2-18', question: 'The term "sovereignty" refers to:', options: ['A state\'s ability to govern itself without external interference', 'A monarch\'s divine right to rule', 'A company\'s control over its brand', 'The power of international law'], correctAnswer: 'A state\'s ability to govern itself without external interference' },
        { id: 'mcq-2-19', question: 'Which of these organizations is primarily focused on lending for development projects?', options: ['World Trade Organization (WTO)', 'International Monetary Fund (IMF)', 'World Bank', 'Amnesty International'], correctAnswer: 'World Bank' },
        { id: 'mcq-2-20', question: 'Cultural appropriation is a controversial aspect of which dimension of globalization?', options: ['Economic', 'Political', 'Cultural', 'Technological'], correctAnswer: 'Cultural' },
    ],
    reels: [
      { id: 'reel-2-1', title: 'Economic Integration', content: 'How global markets are more connected than ever.', imageId: 'reel-2-1' },
      { id: 'reel-2-2', title: 'Cultural Exchange', content: 'The spread of ideas, customs, and media across borders.', imageId: 'reel-2-2' },
    ],
  },
  {
    id: 'humanitarian-issues',
    title: 'Key Concepts and Issues since 1991: Humanitarian Issues',
    content: `
The post-Cold War era has seen numerous {humanitarian_crises}, from genocides to natural disasters. The international community has grappled with the principle of {Responsibility_to_Protect} (R2P), which holds that states have a responsibility to protect their populations from mass atrocities. The role of non-governmental organizations (NGOs) has also grown significantly.
    `,
    summary: 'Examines major humanitarian challenges since 1991, including conflicts, refugees, and the international response to crises.',
    keyTerms: [{ term: 'humanitarian crises' }, { term: 'Responsibility to Protect' }],
    flashcards: [
        { id: 'fc-3-1', question: 'What is the "Responsibility to Protect" (R2P) principle?', answer: 'A global political commitment endorsed by all UN member states in 2005 to prevent genocide, war crimes, ethnic cleansing, and crimes against humanity.' },
        { id: 'fc-3-2', question: 'What are the three pillars of R2P?', answer: '1. The state has the primary responsibility to protect its population. 2. The international community has a responsibility to assist states. 3. The international community has a responsibility to intervene if a state fails to protect its population.' },
        { id: 'fc-3-3', question: 'What is an Internally Displaced Person (IDP)?', answer: 'Someone who is forced to flee their home but remains within their country\'s borders. They are distinct from refugees, who have crossed an international border.' },
        { id: 'fc-3-4', question: 'Name a major humanitarian crisis of the 1990s.', answer: 'The Rwandan Genocide (1994), where an estimated 800,000 people were killed, is a prominent example.' },
        { id: 'fc-3-5', question: 'What is the role of the UNHCR?', answer: 'The United Nations High Commissioner for Refugees is a UN agency with the mandate to protect and support refugees at the request of a government or the UN itself.' },
        { id: 'fc-3-6', question: 'What is the principle of "non-refoulement"?', answer: 'A core principle of international refugee law that forbids a country receiving asylum seekers from returning them to a country in which they would be in likely danger of persecution.' },
        { id: 'fc-3-7', question: 'What is a "complex emergency"?', answer: 'A major humanitarian crisis that is characterized by a combination of factors, including civil conflict, food shortages, and population displacement, requiring a multi-faceted international response.' },
        { id: 'fc-3-8', question: 'What was the significance of the Srebrenica massacre?', answer: 'The 1995 killing of more than 8,000 Bosniak Muslim men and boys in a supposed UN "safe area" during the Bosnian War. It is considered an act of genocide.' },
        { id: 'fc-3-9', question: 'What are the Millennium Development Goals (MDGs)?', answer: 'A set of eight international development goals established following the Millennium Summit of the UN in 2000, with a target date of 2015.' },
        { id: 'fc-3-10', question: 'What are the Sustainable Development Goals (SDGs)?', answer: 'A set of 17 global goals established by the UN in 2015 as a successor to the MDGs, with a target date of 2030. They cover a broad range of social and economic development issues.' },
        { id: 'fc-3-11', question: 'What does "humanitarian intervention" refer to?', answer: 'The use of military force by external actors in a state to prevent or end a humanitarian catastrophe, often without the consent of that state\'s government.' },
        { id: 'fc-3-12', question: 'What is the International Committee of the Red Cross (ICRC)?', answer: 'A humanitarian institution based in Geneva, Switzerland. It is a three-time Nobel Prize laureate and is part of the International Red Cross and Red Crescent Movement.' },
        { id: 'fc-3-13', question: 'What is a "pandemic"?', answer: 'An epidemic of an infectious disease that has spread across a large region, for instance multiple continents or worldwide, affecting a substantial number of people. (e.g., COVID-19).' },
        { id: 'fc-3-14', question: 'How can climate change be considered a humanitarian issue?', answer: 'It exacerbates humanitarian crises by causing extreme weather events, rising sea levels, food and water scarcity, and displacement of populations.' },
        { id: 'fc-3-15', question: 'What is food security?', answer: 'The measure of the availability of food and individuals\' ability to access it. A lack of food security is a major humanitarian concern.' },
        { id: 'fc-3-16', question: 'What is the "CNN effect"?', answer: 'A theory that 24-hour news coverage of humanitarian crises can pressure governments to intervene in situations where they might not otherwise have a national interest.' },
        { id: 'fc-3-17', question: 'What is the "Darfur conflict"?', answer: 'A major armed conflict in the Darfur region of Sudan, which began in 2003 and has been described by some as a genocide.' },
        { id: 'fc-3-18', question: 'What is the purpose of the Geneva Conventions?', answer: 'A series of treaties on the treatment of civilians, prisoners of war (POWs) and soldiers who are otherwise rendered incapable of fighting. They are a cornerstone of international humanitarian law.' },
        { id: 'fc-3-19', question: 'What is a "stateless person"?', answer: 'Someone who is not considered as a national by any state under the operation of its law. They often lack basic rights and access to services.' },
        { id: 'fc-3-20', question: 'What is "checkbook diplomacy" in humanitarian aid?', answer: 'A term used to describe providing funds for humanitarian efforts but being unwilling to commit military forces or take significant political risks.' },
    ],
    mcqs: [
        { id: 'mcq-3-1', question: 'The principle of R2P was notably applied in the international intervention in which country in 2011?', options: ['Syria', 'Iraq', 'Libya', 'Somalia'], correctAnswer: 'Libya' },
        { id: 'mcq-3-2', question: 'Which of the following is an example of a non-governmental organization (NGO) focused on humanitarian aid?', options: ['World Bank', 'Doctors Without Borders (MSF)', 'International Monetary Fund (IMF)', 'World Trade Organization (WTO)'], correctAnswer: 'Doctors Without Borders (MSF)' },
        { id: 'mcq-3-3', question: 'The term "ethnic cleansing" gained prominence during the conflict in which region in the 1990s?', options: ['The Balkans (former Yugoslavia)', 'The Middle East', 'Central Africa', 'Southeast Asia'], correctAnswer: 'The Balkans (former Yugoslavia)' },
        { id: 'mcq-3-4', question: 'What global goals were established by the United Nations in 2015 to address poverty, inequality, and climate change?', options: ['Millennium Development Goals (MDGs)', 'Sustainable Development Goals (SDGs)', 'The Earth Charter', 'The Kyoto Protocol'], correctAnswer: 'Sustainable Development Goals (SDGs)' },
        { id: 'mcq-3-5', question: 'Climate change is increasingly seen as a humanitarian issue because it can cause:', options: ['Displacement of populations', 'Food and water scarcity', 'Increased frequency of natural disasters', 'All of the above'], correctAnswer: 'All of the above' },
        { id: 'mcq-3-6', question: 'A person who has fled their country due to persecution and has crossed an international border is known as a:', options: ['Internally Displaced Person (IDP)', 'Migrant worker', 'Refugee', 'Stateless person'], correctAnswer: 'Refugee' },
        { id: 'mcq-3-7', question: 'The 1994 Rwandan Genocide was a conflict primarily between which two ethnic groups?', options: ['Twa and Hutu', 'Hutu and Tutsi', 'Tutsi and Twa', 'Xhosa and Zulu'], correctAnswer: 'Hutu and Tutsi' },
        { id: 'mcq-3-8', question: 'The Ottawa Treaty, signed in 1997, is a convention to ban:', options: ['Chemical weapons', 'Nuclear weapons', 'Anti-personnel landmines', 'Cluster munitions'], correctAnswer: 'Anti-personnel landmines' },
        { id: 'mcq-3-9', question: 'The Security Council is the most powerful organ of which international body?', options: ['The European Union', 'The World Bank', 'The United Nations', 'NATO'], correctAnswer: 'The United Nations' },
        { id: 'mcq-3-10', question: 'The concept of humanitarian intervention often clashes with which principle of international relations?', options: ['Free trade', 'State sovereignty', 'Collective security', 'Self-determination'], correctAnswer: 'State sovereignty' },
        { id: 'mcq-3-11', question: 'Which of the following is NOT one of the permanent, veto-wielding members of the UN Security Council?', options: ['France', 'Germany', 'China', 'Russia'], correctAnswer: 'Germany' },
        { id: 'mcq-3-12', question: 'The International Criminal Court (ICC) is located in which city?', options: ['New York', 'Geneva', 'The Hague', 'Brussels'], correctAnswer: 'The Hague' },
        { id: 'mcq-3-13', question: 'The 2010 earthquake that caused a massive humanitarian crisis occurred in which Caribbean country?', options: ['Cuba', 'Jamaica', 'Dominican Republic', 'Haiti'], correctAnswer: 'Haiti' },
        { id: 'mcq-3-14', question: 'Amnesty International is an NGO primarily focused on:', options: ['Environmental protection', 'Economic development', 'Human rights', 'Disaster relief'], correctAnswer: 'Human rights' },
        { id: 'mcq-3-15', question: 'The "three pillars" are a framework for which concept?', options: ['The Millennium Development Goals', 'The Geneva Conventions', 'The Responsibility to Protect', 'The Universal Declaration of Human Rights'], correctAnswer: 'The Responsibility to Protect' },
        { id: 'mcq-3-16', question: 'The Syrian Civil War, which began in 2011, has resulted in one of the largest what of the 21st century?', options: ['Economic booms', 'Refugee crises', 'Democratic transitions', 'Technological advancements'], correctAnswer: 'Refugee crises' },
        { id: 'mcq-3-17', question: 'The term "famine" is used to describe an extreme scarcity of:', options: ['Water', 'Medicine', 'Shelter', 'Food'], correctAnswer: 'Food' },
        { id: 'mcq-3-18', question: 'Which body is the main judicial organ of the United Nations?', options: ['International Criminal Court', 'International Court of Justice', 'European Court of Human Rights', 'Permanent Court of Arbitration'], correctAnswer: 'International Court of Justice' },
        { id: 'mcq-3-19', question: 'The 2004 Indian Ocean tsunami was what kind of disaster?', options: ['Geological (Earthquake/Tsunami)', 'Meteorological (Hurricane)', 'Hydrological (Flood)', 'Climatological (Drought)'], correctAnswer: 'Geological (Earthquake/Tsunami)' },
        { id: 'mcq-3-20', question: 'Which of the following is a primary goal of humanitarian action?', options: ['To promote a political agenda', 'To save lives and alleviate suffering', 'To support one side in a conflict', 'To generate profit'], correctAnswer: 'To save lives and alleviate suffering' },
    ],
    reels: [
      { id: 'reel-3-1', title: 'Refugee Crisis', content: 'Understanding the causes and impacts of global displacement.', imageId: 'reel-3-1' },
      { id: 'reel-3-2', title: 'R2P', content: 'The principle of Responsibility to Protect explained.', imageId: 'reel-3-2' },
    ],
  },
  {
    id: 'india-challenges',
    title: 'Contemporary India: Challenges to Peace, Stability, and National Integration',
    content: `
Contemporary India faces numerous challenges. These include regionalism, communalism, and terrorism. The issue of {Kashmir} remains a significant source of conflict with Pakistan. Internally, Naxalite-Maoist insurgency affects several states. The challenge of maintaining national integration in a diverse country is a constant theme in Indian politics.
    `,
    summary: 'An analysis of the internal and external challenges facing India, including regional conflicts, security threats, and issues of national unity.',
    keyTerms: [{ term: 'Kashmir' }],
    flashcards: [
        { id: 'fc-4-1', question: 'What is Communalism in the Indian context?', answer: 'It is an ideology that promotes the interests of a particular religious group, often in opposition to the interests of other groups, posing a threat to national unity.' },
        { id: 'fc-4-2', question: 'What is the Naxalite-Maoist insurgency?', answer: 'A left-wing extremist movement primarily in rural and tribal areas of central and eastern India. They claim to be fighting for the rights of the poor and marginalized.' },
        { id: 'fc-4-3', question: 'Define Regionalism in India.', answer: 'It is a political ideology that focuses on the interests of a particular region or state over the interests of the nation as a whole. It can manifest as demands for more autonomy or separate statehood.' },
        { id: 'fc-4-4', question: 'What is Article 370 of the Indian Constitution, which was revoked in 2019?', answer: 'It granted special autonomous status to the state of Jammu and Kashmir. Its abrogation integrated the region more closely with the rest of India.' },
        { id: 'fc-4-5', question: 'What are some key challenges to India\'s national integration?', answer: 'Casteism, communalism, regionalism, linguistic diversity, and economic inequality are major challenges to maintaining unity in a highly diverse country.' },
        { id: 'fc-4-6', question: 'What is the "Line of Control" (LoC)?', answer: 'The military control line between the Indian and Pakistani controlled parts of the former princely state of Jammu and Kashmir.' },
        { id: 'fc-4-7', question: 'What is the "creamy layer" concept?', answer: 'A term used in India to refer to the relatively wealthier and more educated members of the Other Backward Classes (OBCs) who are not eligible for government-sponsored educational and professional benefit programs.' },
        { id: 'fc-4-8', question: 'What was the Babri Masjid demolition?', answer: 'The 1992 demolition of a 16th-century mosque in Ayodhya by Hindu nationalist activists, which led to widespread communal riots.' },
        { id: 'fc-4-9', question: 'What is the main goal of the Armed Forces (Special Powers) Act, or AFSPA?', answer: 'To grant special powers to the Indian Armed Forces in what the act terms "disturbed areas," including the power to shoot to kill and to arrest without a warrant.' },
        { id: 'fc-4-10', question: 'What is meant by "vote bank" politics?', answer: 'The practice of creating and maintaining a loyal bloc of voters from a single community or caste, who are expected to vote along community lines.' },
        { id: 'fc-4-11', question: 'What was the Mandal Commission?', answer: 'A commission set up in 1979 to identify the socially or educationally backward classes of India and to consider reservations for them in government jobs.' },
        { id: 'fc-4-12', question: 'What is the concept of "secularism" as defined in the Indian Constitution?', answer: 'It means that the state does not have its own religion and treats all religions equally, as opposed to a strict separation of church and state.' },
        { id: 'fc-4-13', question: 'Who are the "Dalits"?', answer: 'A name for people belonging to the lowest caste in India, characterized as "untouchable." The term is a self-chosen political name and means "broken/scattered" in Sanskrit.' },
        { id: 'fc-4-14', question: 'What is a coalition government?', answer: 'A form of government in which political parties cooperate to form a government. India has had numerous coalition governments at the national level since 1989.' },
        { id: 'fc-4-15', question: 'What was Operation Blue Star?', answer: 'A 1984 Indian military operation to remove Sikh separatists from the Golden Temple in Amritsar, which was a highly controversial event.' },
        { id: 'fc-4-16', question: 'What is India\'s "demographic dividend"?', answer: 'The potential for economic growth as the share of the working-age population (15 to 64) is larger than the non-working-age share of the population.' },
        { id: 'fc-4-17', question: 'What is the significance of the 73rd and 74th Constitutional Amendments?', answer: 'They established a system of local self-government in rural (Panchayati Raj) and urban (Municipalities) areas, respectively.' },
        { id: 'fc-4-18', question: 'What is a "Scheduled Tribe" (ST) in India?', answer: 'Communities that are accorded special status by the Constitution of India, often corresponding to indigenous tribal groups.' },
        { id: 'fc-4-19', question: 'What is "sons of the soil" politics?', answer: 'A form of regionalism where preference in jobs and education is demanded for locals or residents of a particular state.' },
        { id: 'fc-4-20', question: 'What is a key feature of India\'s party system?', answer: 'It is a multi-party system, with a large number of national and regional political parties.' },
    ],
    mcqs: [
        { id: 'mcq-4-1', question: 'The Naxalite insurgency has its ideological roots in:', options: ['The Russian Revolution', 'The Chinese Revolution led by Mao Zedong', 'The Cuban Revolution', 'The French Revolution'], correctAnswer: 'The Chinese Revolution led by Mao Zedong' },
        { id: 'mcq-4-2', question: 'Which commission was established to study Centre-State relations in India?', options: ['Mandal Commission', 'Sarkaria Commission', 'Nanavati Commission', 'Liberhan Commission'], correctAnswer: 'Sarkaria Commission' },
        { id: 'mcq-4-3', question: 'The term "Red Corridor" is often used to describe the region in India affected by:', options: ['Communal riots', 'Naxalite insurgency', 'Cross-border terrorism', 'Caste conflicts'], correctAnswer: 'Naxalite insurgency' },
        { id: 'mcq-4-4', question: 'The demand for a separate state of "Bodoland" is an example of regionalism in which Indian state?', options: ['Nagaland', 'Mizoram', 'Assam', 'Manipur'], correctAnswer: 'Assam' },
        { id: 'mcq-4-5', question: 'The primary basis for the reorganization of states in India in 1956 was:', options: ['Religion', 'Geography', 'Language', 'Economic development'], correctAnswer: 'Language' },
        { id: 'mcq-4-6', question: 'The disputed region of Kashmir is a source of conflict between India and which other country?', options: ['China', 'Nepal', 'Pakistan', 'Bangladesh'], correctAnswer: 'Pakistan' },
        { id: 'mcq-4-7', question: 'The demolition of the Babri Masjid in 1992 is a key event related to which issue?', options: ['Casteism', 'Regionalism', 'Communalism', 'Linguistic chauvinism'], correctAnswer: 'Communalism' },
        { id: 'mcq-4-8', question: 'The term "Uniform Civil Code" refers to the proposal to:', options: ['Standardize criminal laws for all citizens', 'Formulate one law for India, applicable to all religious communities in their personal matters', 'Create a common currency for all of South Asia', 'Establish a single language for official use'], correctAnswer: 'Formulate one law for India, applicable to all religious communities in their personal matters' },
        { id: 'mcq-4-9', question: 'Which article of the Indian constitution was abrogated in 2019, removing the special status of Jammu & Kashmir?', options: ['Article 35A', 'Article 370', 'Article 356', 'Article 244'], correctAnswer: 'Article 370' },
        { id: 'mcq-4-10', question: 'India is a secular state, which means:', options: ['The state promotes one religion over others', 'The state is anti-religion', 'The state treats all religions equally', 'Religion is banned from public life'], correctAnswer: 'The state treats all religions equally' },
        { id: 'mcq-4-11', question: 'The movement for a separate state of "Telangana" was successful, leading to its creation from which existing state?', options: ['Karnataka', 'Tamil Nadu', 'Maharashtra', 'Andhra Pradesh'], correctAnswer: 'Andhra Pradesh' },
        { id: 'mcq-4-12', question: 'Which of the following is NOT a fundamental right in the Indian Constitution?', options: ['Right to Equality', 'Right to Work', 'Right to Freedom of Religion', 'Right against Exploitation'], correctAnswer: 'Right to Work' },
        { id: 'mcq-4-13', question: 'The 2002 Gujarat riots are a prominent example of:', options: ['Caste violence', 'Communal violence', 'Naxalite attack', 'A secessionist movement'], correctAnswer: 'Communal violence' },
        { id: 'mcq-4-14', question: 'Panchayati Raj refers to a system of:', options: ['Central government administration', 'State-level judiciary', 'Local self-governance in rural areas', 'Urban planning authorities'], correctAnswer: 'Local self-governance in rural areas' },
        { id: 'mcq-4-15', question: 'Which of the following is a major challenge for India\'s democracy?', options: ['Lack of elections', 'A free press', 'Widespread corruption', 'Absence of political parties'], correctAnswer: 'Widespread corruption' },
        { id: 'mcq-4-16', question: 'The term "Hindu Nationalism" is most often associated with which political ideology?', options: ['Communism', 'Liberalism', 'Hindutva', 'Socialism'], correctAnswer: 'Hindutva' },
        { id: 'mcq-4-17', question: 'The "Green Revolution" in India primarily addressed the challenge of:', options: ['Political instability', 'Food shortages', 'Illiteracy', 'Communalism'], correctAnswer: 'Food shortages' },
        { id: 'mcq-4-18', question: 'Cross-border terrorism in India most commonly refers to attacks emanating from:', options: ['Myanmar', 'Bangladesh', 'Pakistan', 'Sri Lanka'], correctAnswer: 'Pakistan' },
        { id: 'mcq-4-19', question: 'Reservations in jobs and education in India are a form of:', options: ['Negative discrimination', 'Affirmative action', 'Economic sanction', 'Religious persecution'], correctAnswer: 'Affirmative action' },
        { id: 'mcq-4-20', question: 'The official languages of the Union Government of India are:', options: ['English only', 'Hindi only', 'Hindi and English', 'Sanskrit and English'], correctAnswer: 'Hindi and English' },
    ],
    reels: [
      { id: 'reel-4-1', title: 'Kashmir Conflict', content: 'A brief overview of the long-standing issue.', imageId: 'reel-4-1' },
      { id: 'reel-4-2', title: 'National Integration', content: 'The challenges of unity in a diverse nation.', imageId: 'reel-4-2' },
    ],
  },
  {
    id: 'india-governance',
    title: 'Contemporary India: Good Governance',
    content: `
{Good_governance} in India is a major focus. Initiatives like the Right to Information (RTI) Act have aimed to increase transparency and accountability. E-governance projects seek to improve public service delivery. However, corruption remains a significant challenge, and civil society organizations play a crucial role in advocating for reforms.
    `,
    summary: 'This chapter covers the concept of good governance in India, including key reforms, challenges like corruption, and the role of civil society.',
    keyTerms: [{ term: 'Good governance' }],
    flashcards: [
        { id: 'fc-5-1', question: 'What is "Good Governance"?', answer: 'It refers to the process of decision-making and implementation that is participatory, consensus-oriented, accountable, transparent, responsive, effective, equitable, and follows the rule of law.' },
        { id: 'fc-5-2', question: 'What is the main objective of the Right to Information (RTI) Act, 2005?', answer: 'To empower citizens to question the government and its working, thereby promoting transparency and accountability in the working of every public authority.' },
        { id: 'fc-5-3', question: 'What is E-Governance?', answer: 'The use of information and communication technology (ICT) to provide and improve government services, transactions, and interactions with citizens, businesses, and other arms of government.' },
        { id: 'fc-5-4', question: 'What is the role of the Lokpal and Lokayuktas?', answer: 'They are anti-corruption ombudsman bodies in India. The Lokpal has jurisdiction over the central government, and Lokayuktas function at the state level.' },
        { id: 'fc-5-5', question: 'Give an example of a successful e-governance project in India.', answer: 'The Passport Seva Project, which streamlined the process of obtaining a passport, is a widely cited example of successful e-governance.' },
        { id: 'fc-5-6', question: 'What is a "Social Audit"?', answer: 'A process of reviewing official records and determining whether state-reported expenditures reflect the actual money spent on the ground. It is a tool for transparency and accountability.' },
        { id: 'fc-5-7', question: 'What is the "Digital India" campaign?', answer: 'A flagship program of the Government of India with a vision to transform India into a digitally empowered society and knowledge economy.' },
        { id: 'fc-5-8', question: 'What is NITI Aayog?', answer: 'The National Institution for Transforming India, a policy think tank of the Government of India, established to replace the Planning Commission. It aims to foster cooperative federalism.' },
        { id: 'fc-5-9', question: 'What are Citizen\'s Charters?', answer: 'Documents that set out the standards of service, information, and consultation that citizens can expect from a public body, and how to complain if things go wrong.' },
        { id: 'fc-5-10', question: 'What is the "Make in India" initiative?', answer: 'An initiative launched by the Government of India to encourage multi-national, as well as domestic, companies to manufacture their products in India.' },
        { id: 'fc-5-11', question: 'What is "ease of doing business"?', answer: 'An index created by the World Bank to measure how conducive the regulatory environment is to the starting and operation of a local firm.' },
        { id: 'fc-5-12', question: 'What role does civil society play in good governance?', answer: 'Civil society organizations (CSOs) act as watchdogs, advocate for policy changes, and provide services, thereby holding the government accountable and representing citizens\' interests.' },
        { id: 'fc-5-13', question: 'What is the Goods and Services Tax (GST)?', answer: 'A major indirect tax reform in India, which replaced many indirect taxes levied by the central and state governments. It aims to create a single, unified market.' },
        { id: 'fc-5-14', question: 'What is a Public-Private Partnership (PPP)?', answer: 'A long-term arrangement between a government and private sector institutions to provide public assets and services.' },
        { id: 'fc-5-15', question: 'What is the role of the Central Vigilance Commission (CVC)?', answer: 'An apex Indian governmental body created to address governmental corruption. It has the status of an autonomous body, free of control from any executive authority.' },
        { id: 'fc-5-16', question: 'What is the Jan Dhan Yojana?', answer: 'A national mission for financial inclusion to ensure access to financial services, namely banking, savings/deposit accounts, remittance, credit, insurance, and pension in an affordable manner.' },
        { id: 'fc-5-17', question: 'What is judicial activism?', answer: 'A judicial philosophy that motivates judges to depart from traditional precedents in favor of progressive and new social policies. In India, it is often associated with Public Interest Litigation (PIL).' },
        { id: 'fc-5-18', question: 'What is a Public Interest Litigation (PIL)?', answer: 'Litigation filed in a court of law for the protection of "public interest," such as pollution, terrorism, road safety, constructional hazards etc. Any matter where the interest of the public at large is affected can be redressed by filing a PIL.' },
        { id: 'fc-5-19', question: 'What is the "Swachh Bharat Abhiyan" (Clean India Mission)?', answer: 'A country-wide campaign initiated by the Government of India in 2014 to eliminate open defecation and improve solid waste management.' },
        { id: 'fc-5-20', question: 'What is corporate governance?', answer: 'The system of rules, practices, and processes by which a company is directed and controlled. It is a key element of good governance in the private sector.' },
    ],
    mcqs: [
        { id: 'mcq-5-1', question: 'The Right to Information (RTI) Act was passed by the Indian Parliament in which year?', options: ['2001', '2005', '2009', '2013'], correctAnswer: '2005' },
        { id: 'mcq-5-2', question: 'Which of the following is a key pillar of good governance?', options: ['Secrecy', 'Autocracy', 'Transparency', 'Nepotism'], correctAnswer: 'Transparency' },
        { id: 'mcq-5-3', question: 'The concept of "Minimum Government, Maximum Governance" is associated with:', options: ['Improving bureaucratic efficiency and reducing red tape', 'Increasing the size of the government', 'Nationalizing private industries', 'Reducing the powers of the judiciary'], correctAnswer: 'Improving bureaucratic efficiency and reducing red tape' },
        { id: 'mcq-5-4', question: 'MGNREGA (Mahatma Gandhi National Rural Employment Guarantee Act) is an example of a rights-based approach to what?', options: ['Education', 'Information', 'Health', 'Livelihood and social security'], correctAnswer: 'Livelihood and social security' },
        { id: 'mcq-5-5', question: 'The Aadhaar card, which provides a unique identity to residents, is a key component of which government initiative?', options: ['Digital India', 'Make in India', 'Swachh Bharat Abhiyan', 'Ayushman Bharat'], correctAnswer: 'Digital India' },
        { id: 'mcq-5-6', question: 'NITI Aayog replaced which of the following institutions?', options: ['The Finance Commission', 'The Election Commission', 'The Planning Commission', 'The Law Commission'], correctAnswer: 'The Planning Commission' },
        { id: 'mcq-5-7', question: 'The Lokpal is an ombudsman appointed to investigate corruption at which level?', options: ['State Level', 'Municipal Level', 'Central (Union) Level', 'District Level'], correctAnswer: 'Central (Union) Level' },
        { id: 'mcq-5-8', question: 'E-governance refers to the use of what to deliver public services?', options: ['Private couriers', 'Postal services', 'Information and Communication Technology (ICT)', 'Town hall meetings'], correctAnswer: 'Information and Communication Technology (ICT)' },
        { id: 'mcq-5-9', question: 'Which of these is NOT considered a principle of good governance?', options: ['Accountability', 'Rule of Law', 'Inefficiency', 'Participation'], correctAnswer: 'Inefficiency' },
        { id: 'mcq-5-10', question: 'A "Social Audit" is primarily a tool for ensuring:', options: ['Government secrecy', 'Corporate profits', 'Public accountability', 'Election fairness'], correctAnswer: 'Public accountability' },
        { id: 'mcq-5-11', question: 'The introduction of the Goods and Services Tax (GST) is an example of reform in which area?', options: ['Judicial reform', 'Electoral reform', 'Administrative reform', 'Taxation reform'], correctAnswer: 'Taxation reform' },
        { id: 'mcq-5-12', question: 'The "Anna Hazare movement" in 2011 was a major anti-corruption movement that demanded the creation of:', options: ['A new Supreme Court', 'The Lokpal Bill', 'A stronger Election Commission', 'The NITI Aayog'], correctAnswer: 'The Lokpal Bill' },
        { id: 'mcq-5-13', question: 'Public Interest Litigation (PIL) allows citizens to approach which institution for redressal of public grievances?', options: ['The President', 'The Prime Minister', 'The Judiciary', 'The Parliament'], correctAnswer: 'The Judiciary' },
        { id: 'mcq-5-14', question: 'Which government scheme aims to provide health insurance coverage to the poor and vulnerable?', options: ['Jan Dhan Yojana', 'Ayushman Bharat', 'Ujjwala Yojana', 'Swachh Bharat Abhiyan'], correctAnswer: 'Ayushman Bharat' },
        { id: 'mcq-5-15', question: 'The Central Bureau of Investigation (CBI) is India\'s premier agency for:', options: ['Tax collection', 'Foreign intelligence', 'Investigating crime and corruption', 'Conducting elections'], correctAnswer: 'Investigating crime and corruption' },
        { id: 'mcq-5-16', question: 'The term "red tape" is a common metaphor for:', options: ['Efficient public services', 'Excessive bureaucracy and complex rules', 'Transparent governance', 'Rapid decision-making'], correctAnswer: 'Excessive bureaucracy and complex rules' },
        { id: 'mcq-5-17', question: '"Smart Cities Mission" is an urban renewal program with a focus on:', options: ['Historical preservation', 'Rural development', 'Using technology to improve services and infrastructure', 'Agricultural growth'], correctAnswer: 'Using technology to improve services and infrastructure' },
        { id: 'mcq-5-18', question: 'The idea of "cooperative federalism" emphasizes partnership between:', options: ['India and its neighboring countries', 'The public and private sectors', 'The central government and the state governments', 'The executive and the judiciary'], correctAnswer: 'The central government and the state governments' },
        { id: 'mcq-5-19', question: 'Which of the following is a major hurdle for good governance in India?', options: ['Low voter turnout', 'A weak military', 'Widespread illiteracy and poverty', 'Absence of a written constitution'], correctAnswer: 'Widespread illiteracy and poverty' },
        { id: 'mcq-5-20', question: 'The "model code of conduct" is a set of guidelines issued by which body during elections?', options: ['The Supreme Court', 'The Parliament', 'The President\'s Office', 'The Election Commission of India'], correctAnswer: 'The Election Commission of India' },
    ],
    reels: [
      { id: 'reel-5-1', title: 'Right to Information', content: 'Empowering citizens to demand accountability.', imageId: 'reel-5-1' },
      { id: 'reel-5-2', title: 'E-Governance', content: 'Using technology to deliver public services.', imageId: 'reel-5-2' },
    ],
  },
  {
    id: 'india-and-the-world',
    title: 'India and the World',
    content: `
India's foreign policy has evolved since the Cold War. The {Look_East_Policy} (now Act East) signifies a strategic shift towards Southeast Asia. India has also deepened its relationship with the United States and plays a key role in multilateral forums like BRICS and the G20. Its relationship with China and other neighbors remains a central foreign policy challenge.
    `,
    summary: "An exploration of India's foreign policy, its strategic partnerships, and its role in global and regional politics.",
    keyTerms: [{ term: 'Look East Policy' }],
    flashcards: [
        { id: 'fc-6-1', question: 'What was the core principle of India\'s foreign policy during the Cold War?', answer: 'Non-Alignment, which meant not formally aligning with or against any major power bloc (USA or USSR).' },
        { id: 'fc-6-2', question: 'What is the "Act East Policy"?', answer: 'An evolution of the "Look East Policy," it aims to establish deeper and more strategic economic and security cooperation with countries in Southeast and East Asia.' },
        { id: 'fc-6-3', question: 'What is BRICS?', answer: 'An acronym for a group of five major emerging economies: Brazil, Russia, India, China, and South Africa. They seek to enhance their cooperation and influence on the world stage.' },
        { id: 'fc-6-4', question: 'What is India\'s "Neighborhood First" policy?', answer: 'A foreign policy priority that focuses on building friendly and mutually beneficial relationships with its South Asian neighbors.' },
        { id: 'fc-6-5', question: 'What are the main points of contention in the India-China relationship?', answer: 'Border disputes (especially in Ladakh and Arunachal Pradesh), China\'s strategic partnership with Pakistan, and growing economic and regional competition.' },
        { id: 'fc-6-6', question: 'What is the "Gujral Doctrine"?', answer: 'A foreign policy approach from the 1990s where India would be non-reciprocally magnanimous to its smaller neighbors.' },
        { id: 'fc-6-7', question: 'What is the "String of Pearls" theory?', answer: 'A geopolitical theory regarding potential Chinese intentions in the Indian Ocean region. It refers to the network of Chinese military and commercial facilities along its sea lines of communication.' },
        { id: 'fc-6-8', question: 'What is the purpose of the Shanghai Cooperation Organisation (SCO)?', answer: 'A Eurasian political, economic, and security alliance. India and Pakistan joined as full members in 2017.' },
        { id: 'fc-6-9', question: 'What was the significance of the India-US Civil Nuclear Deal?', answer: 'Signed in 2008, it allowed India to access nuclear fuel and technology for civilian purposes despite not being a signatory to the Non-Proliferation Treaty (NPT), marking a major shift in their relationship.' },
        { id: 'fc-6-10', question: 'What is the "Quad" (Quadrilateral Security Dialogue)?', answer: 'A strategic dialogue between the United States, Japan, Australia, and India, widely seen as a response to growing Chinese influence.' },
        { id: 'fc-6-11', question: 'What is SAARC?', answer: 'The South Asian Association for Regional Cooperation, a regional intergovernmental organization of states in South Asia. Its effectiveness has been hampered by India-Pakistan tensions.' },
        { id: 'fc-6-12', question: 'What does "diaspora diplomacy" refer to?', answer: 'A government\'s efforts to engage with its citizens living abroad to advance its national interests. The Indian diaspora is one of the largest in the world.' },
        { id: 'fc-6-13', question: 'What is India\'s position on the UN Security Council reform?', answer: 'India has been actively campaigning for a permanent seat on a reformed and expanded UN Security Council.' },
        { id: 'fc-6-14', question: 'What is the Non-Proliferation Treaty (NPT)?', answer: 'An international treaty whose objective is to prevent the spread of nuclear weapons and weapons technology. India is one of the few countries that has not signed it.' },
        { id: 'fc-6-15', question: 'What is the "Make in India" initiative\'s foreign policy dimension?', answer: 'To attract foreign investment and technology to make India a global manufacturing hub, which also strengthens strategic partnerships.' },
        { id: 'fc-6-16', question: 'What is the "Belt and Road Initiative" (BRI)?', answer: 'A global infrastructure development strategy adopted by the Chinese government. India has raised concerns about the BRI, particularly projects passing through disputed territory.' },
        { id: 'fc-6-17', question: 'What is BIMSTEC?', answer: 'The Bay of Bengal Initiative for Multi-Sectoral Technical and Economic Cooperation. It is seen as a bridge between South and Southeast Asia and an alternative to SAARC for India.' },
        { id: 'fc-6-18', question: 'What is the "two-front war" scenario for India?', answer: 'A military concern for India of having to fight a simultaneous war on its western border with Pakistan and its northern border with China.' },
        { id: 'fc-6-19', question: 'What role does India play in UN peacekeeping operations?', answer: 'India has been one of the largest and most consistent contributors of troops to United Nations peacekeeping missions.' },
        { id: 'fc-6-20', question: 'What is "vaccine maitri" (Vaccine Friendship)?', answer: 'A humanitarian initiative undertaken by the Indian government to provide COVID-19 vaccines to countries around the world.' },
    ],
    mcqs: [
        { id: 'mcq-6-1', question: 'India conducted its first nuclear test, code-named "Smiling Buddha," in which year?', options: ['1962', '1971', '1974', '1998'], correctAnswer: '1974' },
        { id: 'mcq-6-2', question: 'Which of the following organizations is India NOT a permanent member of?', options: ['G20', 'BRICS', 'Shanghai Cooperation Organisation (SCO)', 'UN Security Council'], correctAnswer: 'UN Security Council' },
        { id: 'mcq-6-3', question: 'The "Panchsheel" or the Five Principles of Peaceful Co-existence were first formally enunciated in an agreement between India and which country?', options: ['Pakistan', 'China', 'Soviet Union', 'USA'], correctAnswer: 'China' },
        { id: 'mcq-6-4', question: 'India\'s "Look East Policy" was initiated in the early 1990s by which Prime Minister?', options: ['Atal Bihari Vajpayee', 'P.V. Narasimha Rao', 'Indira Gandhi', 'Manmohan Singh'], correctAnswer: 'P.V. Narasimha Rao' },
        { id: 'mcq-6-5', question: 'The Quadrilateral Security Dialogue (Quad) is a strategic forum comprising India, the United States, Japan, and which other country?', options: ['United Kingdom', 'France', 'Australia', 'South Korea'], correctAnswer: 'Australia' },
        { id: 'mcq-6-6', question: 'The policy of Non-Alignment was a cornerstone of India\'s foreign policy under which Prime Minister?', options: ['Jawaharlal Nehru', 'Lal Bahadur Shastri', 'Indira Gandhi', 'Morarji Desai'], correctAnswer: 'Jawaharlal Nehru' },
        { id: 'mcq-6-7', question: 'The "Shimla Agreement" was signed between India and Pakistan after which conflict?', options: ['1947-48 War', '1965 War', '1971 Bangladesh Liberation War', '1999 Kargil War'], correctAnswer: '1971 Bangladesh Liberation War' },
        { id: 'mcq-6-8', question: 'Which of these is NOT a member of SAARC?', options: ['Afghanistan', 'Bhutan', 'Myanmar', 'Maldives'], correctAnswer: 'Myanmar' },
        { id: 'mcq-6-9', question: 'The 2008 civil nuclear agreement was a landmark deal between India and which country?', options: ['Russia', 'France', 'United States', 'United Kingdom'], correctAnswer: 'United States' },
        { id: 'mcq-6-10', question: 'The "Neighborhood First" policy prioritizes relations with countries in which region?', options: ['Southeast Asia', 'Central Asia', 'South Asia', 'The Middle East'], correctAnswer: 'South Asia' },
        { id: 'mcq-6-11', question: 'India and China have a long-standing border dispute primarily along the:', options: ['Line of Control (LoC)', 'Radcliffe Line', 'McMahon Line', 'Durand Line'], correctAnswer: 'McMahon Line' },
        { id: 'mcq-6-12', question: 'India is a founding member of which of the following groups?', options: ['NATO', 'ASEAN', 'Non-Aligned Movement (NAM)', 'European Union'], correctAnswer: 'Non-Aligned Movement (NAM)' },
        { id: 'mcq-6-13', question: 'The term "diaspora" refers to:', options: ['A country\'s armed forces stationed abroad', 'People who have settled far from their ancestral homelands', 'Foreign tourists visiting a country', 'International students'], correctAnswer: 'People who have settled far from their ancestral homelands' },
        { id: 'mcq-6-14', question: 'The "Gujral Doctrine" related to India\'s policy towards:', options: ['The United States', 'China', 'Its smaller neighbors', 'The European Union'], correctAnswer: 'Its smaller neighbors' },
        { id: 'mcq-6-15', question: 'The "String of Pearls" is a geopolitical theory related to the foreign policy of which country?', options: ['India', 'United States', 'Japan', 'China'], correctAnswer: 'China' },
        { id: 'mcq-6-16', question: 'In which year did India and Pakistan both conduct a series of nuclear tests?', options: ['1995', '1998', '2001', '2004'], correctAnswer: '1998' },
        { id: 'mcq-6-17', question: 'India\'s claim for a permanent seat on the UN Security Council is often grouped with the claims of which other countries (as the G4)?', options: ['Germany, Japan, Brazil', 'South Africa, Nigeria, Egypt', 'UK, France, Russia', 'Canada, Australia, Italy'], correctAnswer: 'Germany, Japan, Brazil' },
        { id: 'mcq-6-18', question: 'Which of the following is an objective of India\'s "Act East" policy?', options: ['To isolate Southeast Asian nations', 'To enhance economic and strategic relations with Southeast Asia', 'To form a military alliance against China', 'To focus solely on cultural exchange'], correctAnswer: 'To enhance economic and strategic relations with Southeast Asia' },
        { id: 'mcq-6-19', question: 'Which country is India\'s largest trading partner in goods (as of the early 2020s)?', options: ['United States', 'UAE', 'Russia', 'China'], correctAnswer: 'China' },
        { id: 'mcq-6-20', question: 'Which of these is a major component of India\'s "soft power"?', options: ['Its nuclear arsenal', 'Its military strength', 'Bollywood, yoga, and cuisine', 'Its defense industry'], correctAnswer: 'Bollywood, yoga, and cuisine' },
    ],
    reels: [
      { id: 'reel-6-1', title: 'Act East Policy', content: 'India\'s pivot towards Southeast and East Asia.', imageId: 'reel-6-1' },
      { id: 'reel-6-2', title: 'India in BRICS', content: 'India\'s role in the bloc of emerging economies.', imageId: 'reel-6-2' },
    ],
  },
];
